
import { Inter } from 'next/font/google'
import './globals.css'
import { ProductosProvider } from "@/context/Context";
import "./fontawesome.min.css";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Marketplace',
  description: 'Generated by create next app',
  manifest: "/manifest.json",
  icons: {
    apple: "/icon.png",
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <link rel="icon" href="icon-192x192.png" />
      <body className={inter.className}>
        <ProductosProvider>{children}</ProductosProvider>
      </body>
    </html>
  );
}
